---
title: "R Command helper"
author: "SL"
output: html_notebook
---

# Environnement

Nettoyage environnement
```{r}
rm(list=ls())
```

Script current directory
```{r}
library(rstudioapi)
current_directory <- dirname(getSourceEditorContext()$path)
```

Working Directory
```{r}
getwd()
setwd(current_directory)
getwd()
```

# Import

See https://www.datacamp.com/community/tutorials/r-data-import-tutorial#data2

Text file -> dataframe
```{r}
df <- read.table(file= "./Data/import.txt", 
                 header = FALSE ,
                 fill = TRUE, #Complete with blank if missing variable on a line
                 stringsAsFactors = TRUE,
                 sep = " " #if needed
                 )
```

CSv file -> dataframe
```{r}
df <- read.csv(file= "./Data/import.csv",
               header = TRUE,
               fill = TRUE, #Complete with blank if missing variable on a line
               stringsAsFactors = TRUE,
               sep = "," #if needed
               )
```

Web file -> Dataframe
```{r}
df <- read.table("https://s3.amazonaws.com/assets.datacamp.com/blog_assets/test.txt", 
                 header = FALSE)
```

With data.table : file-> data.table
```{r}
library(data.table)
df <- data.table::fread("./Data/import.txt") #see help (?fread) for option
```

#Load Save RDS
```{r}
saveRDS(df, "./Data/import.rds")
df <- readRDS("./Data/import.rds")
```

# Data Exploration

Classic
```{r}
str(df)
summary(df)
names(df)
dim(df)
head(df, n = 3)
tail(df)
```







